---
title: "Final Project - Housing Price Analysis"
author: "Xavier Mojica"
date: "2023-04-08"
output: html_document
---
```{r}
#libraries
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(MASS)
library(caret)
library(knitr)
library(rmarkdown)
options(rgl.useNULL=TRUE)
library(qpcR)
library(scales)
library(dplyr)
library(scales)
library(stringr)
library(olsrr)
library(corrplot)
```
```{r}
#Read in Data Sets, Training, Testing 
training = read.csv("/Users/xaviermojica/Desktop/StatsIntro/house-prices-advanced-regression-techniques/train.csv", header = TRUE)
testing = read.csv("/Users/xaviermojica/Desktop/StatsIntro/house-prices-advanced-regression-techniques/test.csv", header = TRUE)
```
```{r}
#Columns Needed: SalePrice,GrLivArea,  Neighborhood = ("NAmes, Edwards, BrkSide")
#Need to Address: Living area = GrLivArea must be in increaments of 100sq ft. 
#Assumptions are met and outliers/influential obs have been id and addressed
#Build Model 
#Provide Estimate and CI for any Estimate 
```
```{r}
# Information about Dataset 
str(training)
str(testing)

```
```{r}
#Realtors prefer to talk about living area in increments of 100 sq. ft. 
#Rounding Living Area Square Footage
training = training %>% mutate(RoundedLivArea = round(GrLivArea, digits = -2))
testing = testing %>% mutate(RoundedLivArea = round(GrLivArea, digits = -2))

#Checking Training and Testing's Rounded Up data
training$RoundedLivArea
testing$RoundedLivArea

#Making Neighborhoods a factor 
training$Neighborhood = as.factor(training$Neighborhood)
testing$Neighborhood = as.factor(testing$Neighborhood)
```
```{r}
# Visualizing Selected Data for Training Data
training %>% filter(Neighborhood %in% c("NAmes","BrkSide","Edwards")) %>% ggplot(aes(x = RoundedLivArea, y = SalePrice, col = Neighborhood)) + geom_point() + geom_jitter() + labs(title = "Rounded Living Area vs. Sale Price", x = "Rouned Living Area", y = "Sale Price")
```
```{r}
#Visualizing Neighborhoods Separately for Training Data 
#Plotting Rounded Living Area vs. Sale Price by Neighborhood

training %>% filter(Neighborhood %in% c("NAmes","BrkSide","Edwards")) %>% ggplot(aes(x = RoundedLivArea, y = SalePrice, col = Neighborhood)) + geom_point() + geom_jitter() + facet_wrap(~Neighborhood, scales = "free") +xlab("Rounded Living Area") + ylab("Sale Price in Dollars") + ggtitle("Rounded Living Area vs. Sale Price by Neighborhood")
```
```{r}
#Checking data for assumptions violations 
training1 = training %>%
filter(Neighborhood %in% c("NAmes","Edwards","BrkSide")) %>%
dplyr::select(SalePrice,Neighborhood,RoundedLivArea)

#Exploring Observations. Validation of assumptions. 
mod_orginal_data = lm(SalePrice~Neighborhood +RoundedLivArea, training1)

res = resid(mod_orginal_data)

#Producing Residuals vs. Fitted Plot 
plot(fitted(mod_orginal_data), res)
#Adding horizontal line at 0 
abline(0,0)

#Creating a QQ Plot for Residuals
qqnorm(res)
#Adding diagonal line 
qqline(res)

#Histogram of Residuals with Curve

ggplot(training1, aes(x=mod_orginal_data$residuals)) + geom_histogram(fill = "steelblue", bins = 39) + labs(title = "Histogram of Residuals", x = "Residuals", y = "Frequency")

#Studentized Residual 
ols_plot_resid_stud_fit(mod_orginal_data)

#Cook's D 
ols_plot_cooksd_chart(mod_orginal_data)
```

```{r}
#Transformation due to Skewness
#Log Transformation
logSalePrice = log(training1$SalePrice)
logRoundedLivArea = log(training1$RoundedLivArea)

logTraining1 = data.frame(logSalePrice,logRoundedLivArea, training1$Neighborhood)

head(logTraining1) #checking log transformations

#Renaming Column training1$Neighborhood to Neighborhood
colnames(logTraining1)[3] = "Neighborhood"
head(logTraining1)
```
```{r}
#Plotting logSalePrice vs. logRoundedLivArea

logTraining1 %>% ggplot(aes(x = logRoundedLivArea, y = logSalePrice, col = Neighborhood)) + geom_point() + geom_jitter() + facet_wrap(~Neighborhood, scales = "free") +xlab("Log Rounded Living Area") + ylab("Log Sale Price in Dollars") + ggtitle("Log Rounded Living Area vs. Log Sale Price by Neighborhood")
```

```{r}

#Checking data for assumptions violations for Log Data
#Exploring Observations. Validation of assumptions. 
modLogData = lm(logSalePrice~Neighborhood + logRoundedLivArea, logTraining1) # using non logged Liv Area #logRoundedLivArea v training1$RoundedLivArea

res = resid(modLogData)

#Producing Residuals vs. Fitted Plot 
plot(fitted(modLogData), res)
#Adding horizontal line at 0 
abline(0,0)

#Creating a QQ Plot for Residuals
qqnorm(res)
#Adding diagonal line 
qqline(res)

#Histogram of Residuals with Curve

ggplot(logTraining1, aes(x=modLogData$residuals)) + geom_histogram(fill = "steelblue", bins = 39) + labs(title = "Histogram of Residuals", x = "Residuals", y = "Frequency")
#Studentized Residual 
ols_plot_resid_stud_fit(modLogData)

#Cook's D 
ols_plot_cooksd_chart(modLogData)
```
```{r}
#Removing Outliers. Looking at both the Original and Log data set
#The two same outliers are present. We will be restricting the domain 
#of the Log data set D:[0,8.25]
x = data.frame(logTraining1$logRoundedLivArea < 8.25)
x # using boolean to see which rows fit criterion 
logTraining1_noOutliers = logTraining1[-c(339,131),]
logTraining1_noOutliers
```
```{r}
#Plotting logSalePrice vs. logRoundedLivArea without 2 Outliers 

logTraining1_noOutliers %>% ggplot(aes(x = logRoundedLivArea, y = logSalePrice, col = Neighborhood)) + geom_point() + geom_jitter() + facet_wrap(~Neighborhood, scales = "free") +xlab("Log Rounded Living Area") + ylab("Log Sale Price") + ggtitle("Log Rounded Living Area vs. Log Sale Price by Neighborhood")
```
```{r}
#Checking data for assumptions violations for Log Data without 2 Outliers. Restricted Domain less than 8.25 logRoundedLivArea
#Exploring Observations. Validation of assumptions. 
modLogDataNoOut = lm(logSalePrice~Neighborhood +logRoundedLivArea, logTraining1_noOutliers)

res = resid(modLogDataNoOut)

#Producing Residuals vs. Fitted Plot 
plot(fitted(modLogDataNoOut), res)
#Adding horizontal line at 0 
abline(0,0)

#Creating a QQ Plot for Residuals
qqnorm(res)
#Adding diagonal line 
qqline(res)

#Histogram of Residuals with Curve

ggplot(logTraining1_noOutliers, aes(x=modLogDataNoOut$residuals)) + geom_histogram(fill = "steelblue", bins = 39) + labs(title = "Histogram of Residuals", x = "Residuals", y = "Frequency")
#Studentized Residual 
ols_plot_resid_stud_fit(modLogDataNoOut)

#Cook's D 
ols_plot_cooksd_chart(modLogDataNoOut)
```
```{r}
#Building Model without Interactions 
#modLogDataNoOut = lm(logSalePrice~Neighborhood +logRoundedLivArea, logTraining1_noOutliers)

summary(modLogDataNoOut)
plot(modLogDataNoOut)
pressmodLogDataNoOut = PRESS(modLogDataNoOut)
pressmodLogDataNoOut$stat


# Calculate Adjusted R-squared
model_summary = summary(modLogDataNoOut)
adjusted_r_squared = model_summary$adj.r.squared
cat("Adjusted R-squared:", adjusted_r_squared, "\n")

#Estimates and CI
coef_estimates_no_outliers = coef(modLogDataNoOut)
conf_intervals_no_outliers = confint(modLogDataNoOut, level = 0.95)
coef_estimates_no_outliers
conf_intervals_no_outliers
```

```{r}
#Plotting Model
########################Need work help on this 
modLogDataNoOut

cf = data.frame(predict(modLogDataNoOut,logTraining1_noOutliers, interval = "confidence"))
p = data.frame(predict(modLogDataNoOut,logTraining1_noOutliers, interval = "prediction"))


modLogDataNoOut %>%
  ggplot(aes(x = logRoundedLivArea, y = logSalePrice, color = Neighborhood)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  facet_wrap(~Neighborhood, scales = "free") +
  labs(title = "Log Rounded Living Area vs. Log Sale Price by Neighborhood",
       x = "Log Rounded Living Area",
       y = "Log Sale Price")
```
```{r}
#Model with Interactions 
fit = lm(logSalePrice~Neighborhood*logRoundedLivArea, logTraining1_noOutliers)
summary(fit)
confint(fit)
plot(fit)
pressfit = PRESS(fit)
pressfit$stat
```
```{r}
# Plotting Interactions
logTraining1_noOutliers %>%
  ggplot(aes(x = logRoundedLivArea, y = logSalePrice, color = Neighborhood)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  facet_wrap(~Neighborhood, scales = "free") +
  labs(title = "Log Rounded Living Area vs. Log Sale Price by Neighborhood",
       x = "Log Rounded Living Area",
       y = "Log Sale Price")



# Lack of Fit Test
## Full and Reduced Model
aov(modLogDataNoOut) %>% summary()
aov(fit) %>% summary()

anova(fit,modLogDataNoOut)

```
```{r}
#Testing our predictions using the full model 
#In order to restrict domain and remove two outliers, we filtered out #GrLivArea #using exp(8.25) which gives us 3800 
#making testing logged

testing$logRoundedLivArea = log(testing$RoundedLivArea)

testing2 = testing %>% filter(Neighborhood %in% c("NAmes", "Edwards", "BrkSide"), GrLivArea <3800) %>% dplyr::select(Id, Neighborhood, GrLivArea, logRoundedLivArea)
conf = data.frame(predict(modLogDataNoOut, testing2, interval = "confidence"))
names(conf) = c("fit", "conf.lwr", "conf.upr")
pred = data.frame(predict(modLogDataNoOut, testing2, interval = "prediction"))
names(pred) = c("fit","pred.lwr","pred.upr")
thetest = conf %>% bind_cols(pred[,2:3], Id = testing2[,1])
thetest
```
```{r}
# With 2 Outliers 

trainingWO = training %>% filter(Neighborhood %in% c("NAmes","Edwards","BrkSide"), GrLivArea>3800) %>% dplyr::select(Id,GrLivArea,RoundedLivArea,SalePrice)

testingWO = testing %>% filter(Neighborhood %in% c("NAmes","Edwards","BrkSide"), GrLivArea>3800) %>% dplyr::select(Id,GrLivArea,RoundedLivArea)

fit1 = lm(log(SalePrice)~log(RoundedLivArea),trainingWO)
pred = data.frame(fit=predict(fit1,testingWO),Id=testingWO$Id)

thetest = thetest %>%
bind_rows(pred)
analysispred = thetest %>%
mutate(fit = exp(fit),
conf.lwr = exp(conf.lwr),
conf.upr = exp(conf.upr),
pred.lwr = exp(pred.lwr),
pred.upr = exp(pred.upr))

summary(modLogDataNoOut)
confint(modLogDataNoOut)
```